-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema onepiececardsdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `onepiececardsdb` ;

-- -----------------------------------------------------
-- Schema onepiececardsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onepiececardsdb` DEFAULT CHARACTER SET utf8 ;
USE `onepiececardsdb` ;

-- -----------------------------------------------------
-- Table `one_piece_card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `one_piece_card` ;

CREATE TABLE IF NOT EXISTS `one_piece_card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `image_url` VARCHAR(2000) NULL,
  `card_type` VARCHAR(45) NOT NULL,
  `attribute` VARCHAR(45) NOT NULL,
  `don_cost` INT NULL,
  `power_level` INT NULL,
  `price` DOUBLE NOT NULL,
  `set` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `color` VARCHAR(45) NOT NULL,
  `rarity` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS onepiecedriver@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'onepiecedriver'@'localhost' IDENTIFIED BY 'onepiecedriver';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'onepiecedriver'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `one_piece_card`
-- -----------------------------------------------------
START TRANSACTION;
USE `onepiececardsdb`;
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (1, 'Zoro', 'DON!!x1 [Your Turn] All of your Characters gain +1000 power.', NULL, 'Leader', 'Slash', NULL, 5000, 208.32, 'Romance Dawn', 'Roronoa', 'Red', 'Leader');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (2, 'Trafalgar', 'Activate: Main] [Once Per Turn] (You may rest the specified number of DON!! cards in your cost area.): If you have 5 Characters, return 1 of your Characters to the owner\'s hand. Then, play up to 1 Character with a cost of 5 or less from your hand that is a different color than the returned Character.', NULL, 'Leader', 'Slash', NULL, 5000, 140.00, 'Romance Dawn', 'Law', 'Red/Green', 'Leader');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (3, 'Luffy', '[Activate: Main] [Once Per Turn] ➃ (You may rest the specified number of DON!! cards in your cost area.): Set up to 1 of your {Supernovas} or {Straw Hat Crew} type Character cards with a cost of 5 or less as active. It gains +1000 power during this turn.', NULL, 'Leader', 'Strike', NULL, 5000, 68.51, 'Romance Dawn', NULL, 'Red/Green', 'Leader');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (4, 'Usopp', '[DON!! x1] [Your Turn] [Once Per Turn] Draw 1 card when your opponent activates an Event.', NULL, 'Character', 'Ranged', 2, 3000, 1.48, 'Romance Dawn', NULL, 'Red', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (5, 'Uta', '[On Play] Add up to 1 red Character card other than [Uta] with a cost of 3 or less from your trash to your hand.', NULL, 'Character', 'Special', 4, 4000, 4.58, 'Romance Dawn', NULL, 'Red', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (6, 'Otama', '[On Play] Give up to 1 of your opponent\'s Characters −2000 power during this turn.', NULL, 'Character', 'Special', 1, 0, 3.22, 'Romance Dawn', NULL, 'Red', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (7, 'Caribou', '[On K.O.] K.O. up to 1 of your opponent\'s Characters with 4000 power or less.', NULL, 'Character', 'Special', 3, 4000, 2.76, 'Romance Dawn', NULL, 'Red', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (8, 'Cavendish', '[On Play] You may add 1 card from your Life area to your hand: This Character gains [Rush] during this turn. (This card can attack on the turn in which it is played.)', NULL, 'Character', 'Slash', 4, 5000, 0.98, 'Romance Dawn', NULL, 'Red', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (9, 'Carrot', '[Trigger] Play this card.', NULL, 'Character', 'Strike', 2, 3000, 0.33, 'Romance Dawn', NULL, 'Red', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (10, 'Gordon', '[On Play] You may place 1 card from your hand at the bottom of your deck: Draw 1 card.', NULL, 'Character', 'Wisdom', 2, 3000, .08, 'Romance Dawn', NULL, 'Red', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (11, 'Sai', NULL, NULL, 'Character', 'Slash', 2, 4000, 2.79, 'Romance Dawn', NULL, 'Red', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (12, 'Sanji', '[Activate: Main] [Once Per Turn] You may add 1 card from your Life area to your hand: This Character gains +2000 power during this turn. Then, give this Character up to 2 rested DON!! cards.', NULL, 'Character', 'Strike', 2, 3000, 77.91, 'Romance Dawn', 'Vinsmoke', 'Red', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (13, 'Jinbe', '[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\n[DON!! x1] [On Block] Play up to 1 red Character card with a cost of 2 or less from your hand.', NULL, 'Character', 'Strike', 4, 5000, 3.72, 'Romance Dawn', NULL, 'Red', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (14, 'Chopper', '[DON!! x1] [When Attacking] You may trash 1 card from your hand: Add up to 1 {Straw Hat Crew} type Character card other than [Tony Tony.Chopper] with a cost of 4 or less from your trash to your hand.', NULL, 'Character', 'Wisdom', 3, 4000, 2.64, 'Romance Dawn', 'Tony Tony', 'Red', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (15, 'Nami', '[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Straw Hat Crew} type card other than [Nami] and add it to your hand. Then, place the rest at the bottom of your deck in any order.', NULL, 'Character', 'Special', 1, 2000, 250.00, 'Romance Dawn', NULL, 'Red', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (16, 'Robin', '[DON!! x1] [When Attacking] K.O. up to 1 of your opponent\'s Characters with 3000 power or less.', NULL, 'Character', 'Strike', 3, 4000, 3.89, 'Romance Dawn', 'Nico', 'Red', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (17, 'Hajrudin', NULL, NULL, 'Character', 'Strike', 4, 6000, 0.03, 'Romance Dawn', NULL, 'Red', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (18, 'Bartolomeo', '[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\n[DON!! x2] [Opponent\'s Turn] This Character gains +3000 power.', NULL, 'Character', 'Special', 2, 2000, 5.55, 'Romance Dawn', NULL, 'Red', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (19, 'Hyogoro', '[Activate: Main] You may rest this Character: Up to 1 of your Leader or Character cards gains +2000 power during this turn.', NULL, 'Character', 'Strike', 2, 3000, 0.28, 'Romance Dawn', NULL, 'Red', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (20, 'Franky', '[DON!! x1] This Character can also attack your opponent\'s active Characters.', NULL, 'Character', 'Ranged', 3, 4000, 4.31, 'Romance Dawn', NULL, 'Red', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (21, 'Brook', '[DON!! x1] [When Attacking] Give up to 2 of your opponent\'s Characters −2000 power during this turn.', NULL, 'Character', 'Slash', 4, 5000, 2.66, 'Romance Dawn', NULL, 'Red', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (22, 'Marco', NULL, NULL, 'Character', 'Special', 3, 5000, 0.79, 'Romance Dawn', NULL, 'Red', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (23, 'Gum', '[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, K.O. up to 1 of your opponent\'s Characters with 4000 power or less.', NULL, 'Event', 'Special', 2, 4000, 3.00, 'Romance Dawn', NULL, 'Red', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (24, 'Oden', '[Activate: Main] [Once Per Turn] You can trash 1 {Land of Wano} type card from your hand: Set up to 2 of your DON!! cards as active.', NULL, 'Leader', 'Slash', NULL, 5000, 22.59, 'Romance Dawn', NULL, 'Green', 'Leader');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (25, 'Killer', '[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\n[DON!! x1] [On Block] If you have 3 or more Characters, draw 1 card.', NULL, 'Character', 'Slash', 2, 2000, 0.22, 'Romance Dawn', NULL, 'Green', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (26, 'Momonosuke', '[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area) You may rest this Character: Look at 5 cards from the top of your deck; reveal up to 1 {Land of Wano} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.', NULL, 'Character', 'Slash', 1, 0, .92, 'Romance Dawn', NULL, 'Green', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (27, 'Komurasaki', '[On Play] ③ (You may rest the specified number of DON!! cards in your cost area.): If your Leader is [Kouzuki Oden], set up to 1 of your {Land of Wano} type Character cards with a cost of 3 or less as active.', NULL, 'Character', 'Wisdom', 1, 0, 1.99, 'Romance Dawn', NULL, 'Green', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (28, 'Jean', NULL, NULL, 'Character', 'Strike', 4, 6000, 0.99, 'Romance Dawn', 'Bart', 'Green', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (29, 'Trafalgar', '[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\n[On Play] You may return 1 Character to your hand: Play up to 1 Character card with a cost of 3 or less from your hand.', NULL, 'Character', 'Slash', 5, 6000, 120.99, 'Romance Dawn', 'Law', 'Green', 'SuperRare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (30, 'Demon', '[Main] K.O. up to 2 of your opponent\'s rested Characters with a cost of 5 or less.', NULL, 'Event', 'Special', 6, NULL, 4.11, 'Romance Dawn', 'Face', 'Green', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (31, 'Doflamingo', '[DON!! x2] [When Attacking] ➀ (You may rest the specified number of DON!! cards in your cost area.): Reveal 1 card from the top of your deck. If that card is a {The Seven Warlords of the Sea} type Character card with a cost of 4 or less, you may play that card rested.', NULL, 'Leader', 'Special', NULL, 5000, 140.00, 'Romance Dawn', 'Donquixote', 'Blue', 'Leader');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (32, 'Kaido', '[DON!! x1] [Your Turn] [Once Per Turn] When your opponent\'s Character is K.O.\'d, add up to 1 DON!! card from your DON!! deck and set it as active.', NULL, 'Leader', 'Strike', NULL, 5000, 80.98, 'Romance Dawn', NULL, 'Blue/Purple', 'Leader');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (33, 'Crocodile', 'Effect\n[DON!! x1] When you activate an Event, you may draw 1 card if you have 4 or less cards in your hand and haven\'t drawn a card using this Leader\'s effect during this turn.', NULL, 'Leader', 'Special', NULL, 5000, 2.55, 'Romance Dawn', NULL, 'Blue/Purple', 'Leader');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (34, 'Alvida', '[DON!! x1] [When Attacking] You may trash 1 card from your hand: Return up to 1 of your opponent\'s Characters with a cost of 3 or less to the owner\'s hand.', NULL, 'Character', 'Strike', 2, 3000, 9.67, 'Romance Dawn', NULL, 'Blue', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (35, 'Caeser', '[On K.O.] Play up to 1 [Smiley] from your deck, then shuffle your deck.', NULL, 'Character', 'Special', 4, 5000, 3.33, 'Romane Dawn', NULL, 'Blue', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (36, 'Mihawk', '[On Play] Place up to 1 Character with a cost of 7 or less at the bottom of the owner\'s deck.', NULL, 'Character', 'Slash', 9, 9000, 7.77, 'Romance Dawn', 'Dracule', 'Blue', 'SuperRare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (37, 'Kuma', '[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\n[On K.O.] Play up to 1 [Pacifista] with a cost of 4 or less from your hand.', NULL, 'Character', 'Strike', 4, 5000, 2.80, 'Romance Dawn', 'Bartholomew', 'Blue', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (38, 'Perona', '[On Play] Look at 5 cards from the top of your deck and place them at the top or bottom of the deck in any order.', NULL, 'Character', 'Special', 1, 2000, 12.99, 'Romance Dawn', NULL, 'Blue', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (39, 'Boa', '[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)\n[DON!! x1] [When Attacking]/[On Block] Draw 1 card if you have 5 or less cards in your hand.', NULL, 'Character', 'Special', 4, 5000, 200.00, 'Romance Dawn', 'Hancock', 'Blue', 'SuperRare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (40, 'Overheat', '[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, return up to 1 active Character with a cost of 3 or less to the owner\'s hand.', NULL, 'Event', 'Special', 2, 4000, 0.66, 'Romance Dawn', NULL, 'Blue', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (41, 'Officer', '[Counter] Play up to 1 {Baroque Works} type Character card with a cost of 3 or less from your hand.', NULL, 'Event', 'Special', 2, NULL, 0.99, 'Romance Dawn', 'Agents', 'Blue', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (42, 'King', '[Your Turn] If you have 10 DON!! cards on your field, give all of your opponent\'s Characters −1000 power.', NULL, 'Leader', 'Special', NULL, 5000, 44.89, 'Romance Dawn', 'Lunarian', 'Purple', 'Leader');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (43, 'Ulti', '[On Play] x1 (You may rest the specified number of DON!! cards in your cost area.): Add up to 1 DON!! card from your DON!! deck and rest it.', NULL, 'Character', 'Strike', 2, 3000, 105.88, 'Romance Dawn', NULL, 'Purple', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (44, 'Kaido', '[On Play] DON!! −6 (You may return the specified number of DON!! cards from your field to your DON!! deck.): If your Leader has the {Animal Kingdom Pirates} type, K.O. all Characters other than this Character.', NULL, 'Character', 'Strike', 10, 12000, 8.55, 'Romance Dawn', NULL, 'Purple', 'SuperRare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (45, 'King', '[On Play] DON!! −2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent\'s Characters with a cost of 3 or less and up to 1 of your opponent\'s Characters with a cost of 2 or less.', NULL, 'Character', 'Special', 7, 7000, 44.99, 'Romance Dawn', 'Lunarian', 'Purple', 'SuperRare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (46, 'Queen', '[On Play] DON!! −1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character gains [Rush] during this turn. Then, give up to 1 of your opponent\'s Characters −2000 power during this turn.\n(This card can attack on the turn in which it is played.)', NULL, 'Character', 'Strike', 6, 5000, 16.37, 'Romance Dawn', NULL, 'Purple', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (47, 'Higurashi', '[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)', NULL, 'Character', 'Special', 2, 3000, 0.50, 'Romance Dawn', 'Kurozumi', 'Purple', 'Common');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (48, 'Ulti', '[Counter] DON!! −2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, draw 1 card.', NULL, 'Event', 'Special', 1, 2000, 1.84, 'Romance Dawn', 'Mortar', 'Purple', 'Uncommon');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (49, 'Thunder', '[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, if you have 2 or less Life cards, add up to 1 DON!! card from your DON!! deck and rest it.', NULL, 'Event', 'Special', 2, 4000, 5.63, 'Romance Dawn', 'Bagua', 'Purple', 'Rare');
INSERT INTO `one_piece_card` (`id`, `first_name`, `description`, `image_url`, `card_type`, `attribute`, `don_cost`, `power_level`, `price`, `set`, `last_name`, `color`, `rarity`) VALUES (50, 'Shanks', '[Rush] (This card can attack on the turn in which it is played.)\n[When Attacking] Your opponent cannot activate a [Blocker] Character that has 2000 or less power during this battle.', NULL, 'Character', 'Slash', 9, 10000, 1200, 'Romance Dawn', NULL, 'Red', 'Secret');

COMMIT;

